#!/usr/bin/env bash
# setting up the 404 page

sudo apt-get update
sudo apt-get -y nginx

echo "Hello Wolrd!" | sudo tee /var/www/html/index.html

custom_config="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Dedeyd70 permanent;"

sudo sed -i "s/server_name _;/$custom_config/" /etc/nginx/sites-enabled/default

#creating a 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

sudo sed -i "s/listen 80 default_server;/$custom_config/" /etc/nginx/sites-enabled/default

sudo service nginx restart
