#!/usr/bin/env bash
# A script that creates the file /var/run/myscript.pd

fig1=5
fig2=4

killer()
{
	rm /var/run/myscript.pid
	exit
}

echo "$$" > /var/run/myscript.pid

while [ "$fig2" -lt $fig1 ]; do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'echo "I hate the kill command" && killer' SIGTERM
	trap 'killer' SIGQUIT 
done
