#!/usr/bin/env bash
# A script that displays To infinity and beyond indefinitely.
# In between each iteration of the loop, add a sleep 2

fig1=5
fig2=4

while [ "$fig2" -lt $fig1 ]
do
	echo "To infinity and beyond"
	sleep 2
done
