#!/usr/bin/env bash
# Indefinitely writes I am alive! to the file /tmp/my_process
# In between every I am alive! message, the program should pause for 2 seconds.

fig1=5
fig2=4

while [ "$fig2" -lt $fig1 ]
do
	echo "I am alive!" >> /tmp/my_process
	sleep 2
done
