#!/usr/bin/env bash
# A script that displays the content of the file /etc/passwd
# Script should display username, user id and home directory path for the user.

while IFS= read -r username uid home_dir _; do
  echo "$username $uid $home_dir"
done < "/etc/passwd"
