#!/usr/bin/env bash
# this script uses a while loop and on 9th iteration displays Best school and Hi.

num=0

while [ $num -lt 10 ]
do
	if [ $num -eq 9 ]
	then
		echo "Hi"
	fi
		echo "Best School"
	((num++))
done
