#!/usr/bin/env bash
# This script uses the while loop to display:
# bad luck for 4th iteration
# good luck for 8th iteration and best school for the other iterations.

num=1

while [ $num -lt 11 ]
do
	if [ $num -eq 4 ]
	then
		echo "bad luck"
	elif [ $num -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( num++))
done
