#!/usr/bin/env bash
# A script that displays the time for 12 hours and 59 minutes;
# Displaying hours from 0 to 12
# Displaying minutes from 1 to 59

hr=0

while [ $hr -le 12 ]
do
  echo "hour: $hr"
  mins=1
  while [ $mins -le 59 ]
  do
    echo "$mins"
    mins=$((mins+1))
  done
  hr=$((hr+1))
done
