#!/usr/bin/env bash
# Install the ufw firewall and setup a few rules on web-01
# except for TCP ports 22, 443 and 80.

sudo apt-get update
sudo apt-get install -y ufw

sudo ufw default deny incoming
sudo ufw default allow outgoing

sudo ufw allow 22/tcp
sudo ufw enable
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
